apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.djangoSvc.name }}"
spec:
  ports:
  - port: {{ .Values.djangoSvc.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.djangoSvc.ports.targetPort }}
  selector:
    app: "{{ .Values.djangoSvc.app }}"
  type: NodePort
