apiVersion: v1
kind: Endpoints
metadata:
  name: "{{ .Values.postgresSvc.name }}"
subsets:
  - addresses:
      - ip: {{ .Values.postgresEndpoint.subsets.ip }}
    ports:
      - port: {{ .Values.postgresSvc.ports.targetPort }}
