apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.redisSvc.name }}"
spec:
  selector:
    pod: {{ .Values.redis.labels.pod }}
  ports:
  - port: {{ .Values.redisSvc.ports.port }}
    targetPort: {{ .Values.redisSvc.ports.targetPort }}
