kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.postgresSvc.name }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.postgresSvc.app }}"
  ports:
  - port: {{ .Values.postgresSvc.ports.port }}
