kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.postgresSvc.name }}"
spec:
  selector:
    app: "{{ .Values.postgresSvc.app }}"
  ports:
  - port: {{ .Values.postgresSvc.ports.port }}
    targetPort: {{ .Values.postgresSvc.ports.targetPort }}
